# Generated by Django 4.2.1 on 2023-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('mobile_model', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('complaint', models.TextField()),
                ('remark_status', models.CharField(max_length=100)),
                ('technition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('mobile_number', models.IntegerField()),
                ('emp_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
