# Generated by Django 4.2.1 on 2023-11-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_details_complaint_alter_details_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='roll_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
