# Generated by Django 4.2.1 on 2023-11-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_admin_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_log',
        ),
        migrations.AlterField(
            model_name='staff',
            name='emp_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile_number',
            field=models.CharField(max_length=100),
        ),
    ]
